name: webinar1_projek_starter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/shoes_01.png
    - assets/shoes_02.png
    - assets/store.png
    - assets/profile.png
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/Helvetica-Bold-Font.ttf

    - family: Raleway
      fonts:
        - asset: assets/Raleway-Regular.ttf

    - family: CustomIcon
      fonts:
        - asset: assets/CustomIcon.ttf